language: java
install:
  - mvn install -DskipTests -DskipKTest
  - sudo apt-get install texlive-latex-base
script: mvn verify -Dbase=HEAD^1 $FLAGS
jdk:
  - oraclejdk8
env:
  - PATH=$PATH:$TRAVIS_BUILD_DIR/k/k-distribution/target/release/k/bin FLAGS="-DktestDir=tutorial"
  - PATH=$PATH:$TRAVIS_BUILD_DIR/k/k-distribution/target/release/k/bin FLAGS="-DktestDir=samples"
  - PATH=$PATH:$TRAVIS_BUILD_DIR/k/k-distribution/target/release/k/bin FLAGS="-DktestDir=tests/newparser -Dconfig=config.xml"
  - PATH=$PATH:$TRAVIS_BUILD_DIR/k/k-distribution/target/release/k/bin FLAGS="-DktestDir=tests/regression -Dconfig=config.xml"
